# Use Node.js base image
FROM node:22-alpine

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and packge-lock.json first (for caching dependencies)
COPY package*.json ./

# Install all dependencies (including devDep)
RUN npm install

# Copy all project files
COPY . .

# Expose the application port
EXPOSE 4000

# Use nodemon for hot-reloading
CMD ["npm", "run", "test:watch"]