name: Deploy NestJS App to AWS

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: contains(join(github.event.commits.*.modified, ' '), '.tf')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.AWS_ECR_URL }}:latest .
      - name: Push to ECR
        run: docker push ${{ secrets.AWS_ECR_URL }}:latest

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ${{ secrets.AWS_ECS_CLUSTER }} --service ${{ secrets.AWS_ECS_SERVICE }} --force-new-deployment